codeplus/xava/carts/models.py
from shop.extensions import db    

codeplus/xava/main/models.py
from shop.extensions import db    

codeplus/xava/products/models.py
from xava.extensions import db  
from datetime import datetime


class Addproduct(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    price = db.Column(db.Numeric(10, 2), nullable=False)
    discount = db.Column(db.Integer, default=0)
    stock = db.Column(db.Integer, nullable=False)
    colors = db.Column(db.Text, nullable=False)
    description = db.Column(db.Text, nullable=False)
    pub_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    brand_id = db.Column(db.Integer, db.ForeignKey("brand.id"), nullable=False)
    brand = db.relationship("Brand", backref=db.backref("brands", lazy=True))

    category_id = db.Column(db.Integer, db.ForeignKey("category.id"), nullable=False)
    category = db.relationship("Category", backref=db.backref("categories", lazy=True))


def __repr__(self):
    return "<Addproduct %r>" % self.name


class Brand(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False, unique=True)


def __repr__(self):
    return "<Brand %r>" % self.name


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False, unique=True)


def __repr__(self):
    return "<Category %r>" % self.name

codeplus/xava/__init__.py
from flask import Flask

from config import Config
from .extensions import db, bcrypt

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    bcrypt.init_app(app)

    
    # Register blueprints here
    from .main.routes import main
    app.register_blueprint(main, url_prefix='/')

    from .auth.routes import auth
    app.register_blueprint(auth, url_prefix='/auth')

    from .carts.routes import carts
    app.register_blueprint(carts, url_prefix='/carts')
    
    from .products.routes import products
    app.register_blueprint(products, url_prefix='/products')

    return app

codeplus/xava/carts/routes.py
from flask import Blueprint


carts = Blueprint("carts", __name__)

codeplus/xava/main/routes.py
from flask import Blueprint, request, url_for, redirect, render_template, flash


main = Blueprint("main", __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('main/home.html', title='Home Page')


@main.route('/')
@main.route('/about')
def about():
    return render_template('main/about.html', title='About Page')

codeplus/xava/products/routes.py
from flask import Blueprint, redirect, request,render_template, session,flash,url_for
from ..extensions import db
from .models import Brand, Category, Addproduct
from .form import Addproducts


products = Blueprint("products", __name__)


@products.route('/')
def index():
    return render_template('index.html')

codeplus/xava/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}</dt>
<dd>
  {{ field(**kwargs)|safe }} {% if field.errors %}
  <ul class="errors">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</dd>
{% endmacro %}

codeplus/xava/templates/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="flashes">
  {% for category, message in messages %}
  <div class="alert text-center alert-{{ category }}">
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% endwith %}

codeplus/xava/templates/_navbar v2.html
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mr-auto">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Home</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">All Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Category</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              BB
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item" href="#">A</a>
              </li>

            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class=" d-grid gap-2  d-md-flex justify-content-md-end">
          <button type="button" class="btn text-light btn-sm me-md-2" data-bs-toggle="modal"
            data-bs-target="#ModalForm">Log in</button>
          <button type="button" class="btn text-light btn-sm me-md-2" data-bs-toggle="modal"
            data-bs-target="#ModalForm1">Register</button>
          <button type="button" class="btn text-light btn-sm">Logout</button>
        </form>
      </div>
    </div>
  </nav>
</div>

<div class="modal fade" id="ModalForm" tabindex="-1" data-bs-backdrop="static" aria-labelledby="ModalFormLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        {% from "_formhelpers.html" import render_field %}
        <div class="myform bg-dark">
          <h1 class="text-center  w-100 font-weight-bold">Login to Codeplus</h1>
          <form method="POST" enctype="multipart/form-data">
            <div>
              {{ render_field(form.email, class="form-control " ,
              id="exampleInputEmail1",for="exampleInputEmail1",type="email") }}
              {{ render_field(form.password, class="form-control",type="password", class="form-control",
              id="exampleInputPassword1") }}
            </div>
            <div class="modal-footer">
              <p>
                <button type="button" class="btn btn-sm btn-light" data-bs-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-sm btn-light">Login</button>
              </p>
              <p>Not a member? <a href="#">Signup now</a></p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>























<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Login to Codeplus</h1>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3 mt-4">
            <label for="recipient-name" class="col-form-label">Email</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Password:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Login</button>
      </div>
    </div>
  </div>
</div>

codeplus/xava/templates/_navbar.html
<!-------------Navbar Start here------------->
<header class=site-header>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTloxi"
                aria-controls="navbarTloxi" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Codeplus</a>
            <div class="collapse navbar-collapse" id="navbarTloxi">
                <div class="navbar-nav me-auto mb-2 mb-lg-0">
                    <a class="nav-link nav-item" href="">Home</a>
                    <a class="nav-link nav-item" href="">About</a>
                </div>
                <div class="d-flex navbar-nav">
                    <a class="nav-link nav-item" href="">Account details</a>
                    <a class="nav-link nav-item" href="">Logout</a>
                    <a class="nav-link nav-item" href="">Login</a>
                    <a class="nav-link nav-item" href="">Register</a>
                </div>
            </div>
        </div>
    </nav>
</header>
<!-------------Navbar Ends here-->

codeplus/xava/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename = '/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = '/bs-icons/bootstrap-icons.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename = '/css/main.css')}}">
    <title>{{title}}-ERP</title>
</head>

<body>
    <!-------------Navbar Start here------------->
    <header class=site-header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark bg-steel fixed-top">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTloxi"
                    aria-controls="navbarTloxi" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#">Codeplus</a>
                <div class="collapse navbar-collapse" id="navbarTloxi">
                    <div class="navbar-nav me-auto mb-2 mb-lg-0">
                        <a class="nav-link nav-item" href="{{url_for('main.home')}}">Home</a>
                        <a class="nav-link nav-item" href="{{url_for('main.about')}}">About</a>
                    </div>
                    <div class="d-flex navbar-nav">
                        <a class="nav-link nav-item" href="#">Account Details</a>
                        <a class="nav-link nav-item" href="#">Logout</a>
                        <a class="nav-link nav-item" href="{{url_for('auth.login')}}">Login</a>
                        <a class="nav-link nav-item" href="{{url_for('auth.register')}}">Register</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!-------------Navbar Ends here-->


    <main role=" main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% include '_messages.html' %}
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class="text-muted">You can put any info here if you would like to</p>
                    <ul>
                        <li>Latest post</li>
                        <li>Anoucement</li>
                        <li>Calender</li>
                        <li>etc</li>
                    </ul>
                </div>
            </div>
        </div>
    </main>


    <script src="{{url_for('static', filename = " /js/popper.min.js")}}"></script>
    <script src="{{url_for('static', filename = " /js/bootstrap.min.js")}}"></script>
    <script src="{{url_for('static', filename = " /js/jquery.js")}}"></script>
</body>

</html>

codeplus/xava/templates/main/about.html
{% extends 'layout.html' %}
{% block content %}
<h1>Codeplus Pro</h1>
{% endblock %}

codeplus/xava/templates/main/home.html
{% extends 'layout.html' %}
{% block content %}
<h1>Codeplus Pro</h1>
{% endblock %}